include:
  - project: 'mauricewipf/playground-gitlab'
    ref: master
    file: '/shared/.gitlab-ci-templates.yml'
#  - local: '/ci-scripts/.templates.yml'
#  - remote: 'https://raw.githubusercontent.com/example/repo/main/templates/build.yml'

stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: "docker.io/mauricewipf/playground-nextjs"
  IMAGE_TAG: "v0.0.9"
  DOCKERFILE_PATH: "k8s/playground-nextjs/Dockerfile"
  HELM_CHART_NAME: "playground-nextjs"
  HELM_CHART_PATH: "./k8s/playground-nextjs"

build:
  stage: build
  extends:
    - .docker_build_image
    - .docker_push_image

test:
  stage: test
  extends:
    - .test_image

deploy:
  stage: deploy
  extends:
    - .prepare_kubeconfig_and_helm_upgrade
