# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.secret.MINIO_ACCESS_KEY | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.secret.MINIO_SECRET_KEY | b64enc | quote }}