apiVersion: v1
kind: Service
metadata:
  name: {{ include "playground-minio.fullname" . }}
  labels:
    {{- include "playground-minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      protocol: TCP
      name: api
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "playground-minio.selectorLabels" . | nindent 4 }}
